name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Build The Docker Image
        run: docker build . --file DockerFile
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up Python
        uses: actions/setup-python
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest

      - name: Run tests
        run: |
          pytest

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action

      - name: Login to DockerHub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          file: ./DockerFile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
